export const langs = {
    es: {
        statment : "<p class='p1'>Pipoca es un proyecto musical que utiliza procesos de inteligencia artificial como herramienta de exploración y creación, no como un fin, sino como un medio. Usamos la IA para explorar géneros musicales, tradiciones y cruces culturales que nos interesan. El proceso parte de ideas abiertas y, a partir de lo que aparece, seleccionamos, curamos, editamos e intervenimos el material hasta llevarlo a un lugar que tenga sentido para nosotros.</p><p>Para nosotros, la inteligencia artificial no sustituye la práctica musical ni busca reemplazar a músicos o productores; es una herramienta más que amplía las formas posibles de investigar, componer y producir música.</p><p>No estamos cerrados a esta tecnología: hoy usamos estas herramientas, más adelante puede ser distinto. Estamos abiertos a colaborar con músicos, productores y artistas y, si en algún momento sentimos que la inteligencia artificial deja de aportar a lo que buscamos, simplemente dejaremos de usarla.</p>"
    },
    en: {
        statment: "<p class='p1'>Pipoca is a music project that uses artificial intelligence processes as a tool for exploration and creation, not as an end, but as a means. We use AI to explore musical genres, traditions and cultural intersections that interest us. The process starts from open ideas and, from what emerges, we select, curate, edit and intervene in the material until it reaches a place that makes sense to us.</p><p>For us, artificial intelligence does not replace musical practice nor seek to replace musicians or producers; it is simply another tool that expands the ways music can be researched, composed and produced.</p><p>We are not fixed to this technology: we use these tools today, but that may change in the future. We are open to collaborating with musicians, producers and artists and, if at some point artificial intelligence no longer contributes to what we are looking for, we will simply stop using it.</p>"
    },
    fr: {
        statment: "<p class='p1'>Pipoca est un projet musical qui utilise des processus d’intelligence artificielle comme outil d’exploration et de création, non comme une finalité, mais comme un moyen. Nous utilisons l’IA pour explorer des genres musicaux, des traditions et des croisements culturels qui nous intéressent. Le processus part d’idées ouvertes et, à partir de ce qui émerge, nous sélectionnons, curons, éditons et intervenons sur la matière jusqu’à atteindre un résultat qui a du sens pour nous.</p><p>Pour nous, l’intelligence artificielle ne remplace pas la pratique musicale et ne cherche pas à remplacer les musiciens ou les producteurs ; c’est un outil supplémentaire qui élargit les façons possibles de rechercher, composer et produire de la musique.</p><p>Nous ne sommes pas attachés à cette technologie : aujourd’hui nous l’utilisons, mais cela pourra évoluer. Nous sommes ouverts aux collaborations avec des musiciens, producteurs et artistes et, si à un moment donné l’intelligence artificielle ne contribue plus à ce que nous recherchons, nous cesserons simplement de l’utiliser.</p>"
    },
    pt: {
        statment: "<p class='p1'>Pipoca é um projeto musical que utiliza processos de inteligência artificial como ferramenta de exploração e criação, não como um fim, mas como um meio. Usamos a IA para explorar gêneros musicais, tradições e cruzamentos culturais que nos interessam. O processo parte de ideias abertas e, a partir do que surge, selecionamos, curamos, editamos e intervimos no material até levá-lo a um lugar que faça sentido para nós.</p><p>Para nós, a inteligência artificial não substitui a prática musical nem busca substituir músicos ou produtores; é apenas mais uma ferramenta que amplia as formas possíveis de pesquisar, compor e produzir música.</p><p>Não estamos presos a essa tecnologia: hoje usamos essas ferramentas, mas isso pode mudar. Estamos abertos a colaborar com músicos, produtores e artistas e, se em algum momento a inteligência artificial deixar de contribuir para o que buscamos, simplesmente deixaremos de usá-la.</p>"
    },
    de : {
        statment: "<p class='p1'>Pipoca ist ein Musikprojekt, das Prozesse der künstlichen Intelligenz als Werkzeug für Exploration und Kreation nutzt, nicht als Zweck, sondern als Mittel. Wir verwenden KI, um musikalische Genres, Traditionen und kulturelle Überschneidungen zu erkunden, die uns interessieren. Der Prozess beginnt mit offenen Ideen und aus dem, was entsteht, wählen wir aus, kuratieren, bearbeiten und greifen in das Material ein, bis es einen Punkt erreicht, der für uns Sinn ergibt.</p><p>Für uns ersetzt künstliche Intelligenz keine musikalische Praxis und hat nicht das Ziel, Musiker oder Produzenten zu ersetzen; sie ist ein weiteres Werkzeug, das die möglichen Wege erweitert, Musik zu erforschen, zu komponieren und zu produzieren.</p><p>Wir sind nicht an diese Technologie gebunden: Heute nutzen wir diese Werkzeuge, in Zukunft kann sich das ändern. Wir sind offen für die Zusammenarbeit mit Musikern, Produzenten und Künstlern und wenn künstliche Intelligenz irgendwann keinen Beitrag mehr zu dem leistet, was wir suchen, werden wir sie einfach nicht mehr verwenden.</p>"
    }
}


